# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ebc1b2dd0c66c445113d989547b22b4f609a8a9cfccb03a9f7e9b13ff28bb589e32c345eb6ddc29e6f315ba34afe7f2e0f592ead7c668d65d2ebb97bee520ae5

test:
  secret_key_base: 5a4a54baac2fcc346a28f21ccd06b4352655bfddcca5dfa89240d4d9328245c63a92078a8f0f5f0daf0a896ec67965f8624bb2fbcc93c0696dd7ad1a9cfa2980

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
